### ISSUE TITLE
Rendering issue under windows: pyglet must be updated

### ISSUE THREAD

**Issue by aiAdrian** [flatland-association/flatland-rl#53]
**Description**
Flatland 4.0.0 doesn't work under Windows with python 3.8< due of a pyglet 1.3.2 issue 
https://github.com/mmatl/pyrender/issues/95

**To Reproduce**
List the steps needed to reproduce the behavior:

Windows: 
1. conda create python=3.8 --name flatland_4_0_0
2. conda activate flatland_4_0_0 
3. python custom_railmap_example.py

**Tracer**
Traceback (most recent call last):
  File "custom_railmap_example.py", line 129, in <module>
    main(sys.argv[1:])
  File "custom_railmap_example.py", line 122, in main
    custom_railmap_example(sleep_for_animation, do_rendering)
  File "custom_railmap_example.py", line 95, in custom_railmap_example
    env_renderer.render_env(show=True, show_observations=False)
  File "C:\Users\u216993\AppData\Local\miniconda3\envs\flatland_4_0_0\lib\site-packages\flatland\utils\rendertools.py", line 62, in render_env
    return self.renderer.render_env(show, show_agents, show_inactive_agents, show_observations,
  File "C:\Users\u216993\AppData\Local\miniconda3\envs\flatland_4_0_0\lib\site-packages\flatland\utils\rendertools.py", line 526, in render_env
    return self.render_env_svg(show=show,
  File "C:\Users\u216993\AppData\Local\miniconda3\envs\flatland_4_0_0\lib\site-packages\flatland\utils\rendertools.py", line 761, in render_env_svg
    self.gl.show()
  File "C:\Users\u216993\AppData\Local\miniconda3\envs\flatland_4_0_0\lib\site-packages\flatland\utils\graphics_pgl.py", line 56, in show
    self.open_window()
  File "C:\Users\u216993\AppData\Local\miniconda3\envs\flatland_4_0_0\lib\site-packages\flatland\utils\graphics_pgl.py", line 24, in open_window
    self.window = pgl.window.Window(resizable=True, vsync=False, width=1200, height=800)
  File "C:\Users\u216993\AppData\Local\miniconda3\envs\flatland_4_0_0\lib\site-packages\pyglet\__init__.py", line 384, in __getattr__
    __import__(import_name)
  File "C:\Users\u216993\AppData\Local\miniconda3\envs\flatland_4_0_0\lib\site-packages\pyglet\window\__init__.py", line 1896, in <module>
    gl._create_shadow_window()
  File "C:\Users\u216993\AppData\Local\miniconda3\envs\flatland_4_0_0\lib\site-packages\pyglet\gl\__init__.py", line 208, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "C:\Users\u216993\AppData\Local\miniconda3\envs\flatland_4_0_0\lib\site-packages\pyglet\window\win32\__init__.py", line 134, in __init__
    super(Win32Window, self).__init__(*args, **kwargs)
  File "C:\Users\u216993\AppData\Local\miniconda3\envs\flatland_4_0_0\lib\site-packages\pyglet\window\__init__.py", line 501, in __init__
    display = get_platform().get_default_display()
  File "C:\Users\u216993\AppData\Local\miniconda3\envs\flatland_4_0_0\lib\site-packages\pyglet\window\__init__.py", line 1845, in get_default_display
    return pyglet.canvas.get_display()
  File "C:\Users\u216993\AppData\Local\miniconda3\envs\flatland_4_0_0\lib\site-packages\pyglet\canvas\__init__.py", line 77, in get_display
    from pyglet.app import displays
  File "C:\Users\u216993\AppData\Local\miniconda3\envs\flatland_4_0_0\lib\site-packages\pyglet\app\__init__.py", line 175, in <module>
    event_loop = EventLoop()
  File "C:\Users\u216993\AppData\Local\miniconda3\envs\flatland_4_0_0\lib\site-packages\pyglet\app\base.py", line 119, in __init__
    self.clock = clock.get_default()
  File "C:\Users\u216993\AppData\Local\miniconda3\envs\flatland_4_0_0\lib\site-packages\pyglet\__init__.py", line 384, in __getattr__
    __import__(import_name)
  File "C:\Users\u216993\AppData\Local\miniconda3\envs\flatland_4_0_0\lib\site-packages\pyglet\clock.py", line 166, in <module>
    _default_time_function = time.clock
A

**Comment by aiAdrian** [comment]
(flatland_4_0_0) C:\devsbb\workspace\flatland\flatland-rl\examples>pip install upgrade pyglet
ERROR: Could not find a version that satisfies the requirement upgrade (from versions: none)
ERROR: No matching distribution found for upgrade

(flatland_4_0_0) C:\devsbb\workspace\flatland\flatland-rl\examples>pip install pyglet -U
Requirement already satisfied: pyglet in c:\users\u216993\appdata\local\miniconda3\envs\flatland_4_0_0\lib\site-packages (1.3.2)
Collecting pyglet
  Using cached pyglet-2.0.9-py3-none-any.whl.metadata (8.4 kB)
Downloading pyglet-2.0.9-py3-none-any.whl (854 kB)
   ---------------------------------------- 854.7/854.7 kB 2.0 MB/s eta 0:00:00
Installing collected packages: pyglet
  Attempting uninstall: pyglet
    Found existing installation: pyglet 1.3.2
    Uninstalling pyglet-1.3.2:
      Successfully uninstalled pyglet-1.3.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gym 0.14.0 requires pyglet<=1.3.2,>=1.2.0, but you have pyglet 2.0.9 which is incompatible.
Successfully installed pyglet-2.0.9


** resolves the problem **

**Comment by fnberta** [comment]
Ok, so the culprit here is that we currently pin gym to version `0.14.0` which then depends on an old version of `pyglet`. I tried to update `gym` in https://github.com/flatland-association/flatland-rl/pull/55, but only partly succeeded. Please see the PR for more info.

Also, tackling https://github.com/flatland-association/flatland-rl/issues/26 would really simplify resolving this issue. Is this something that could be done rather quickly?

**Comment by fnberta** [comment]
Thanks to your work in https://github.com/flatland-association/flatland-rl/pull/56, we can fix this in https://github.com/flatland-association/flatland-rl/pull/57.
